### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by ndench**
Pretty much just copied liip/LiipTestFixturesBundle#80.

Closes: #575

### CODE REVIEW

**Comment by ndench** [comment]
Runs fine on 8.0 with Symfony 4.4. But gets version conflicts for 3.4 and 4.4. Not really sure on how we should solve this.

**Comment by alexislefebvre** [comment]
Feel free to remove Symfony 3.4 and the `--prefer-lowest` option.

**Comment by alexislefebvre** [comment]
If you rebase on master, please add PHP 8.0 in that file: https://github.com/liip/LiipFunctionalTestBundle/blob/99773a1d732fcd691ab88440d49548ee378b5d47/.github/workflows/tests.yml

**Comment by ndench** [comment]
Thanks @alexislefebvre, I've made those changes and now it passes :smile:

**Comment by alexislefebvre** [comment]
Awesome, thanks!

**Comment by alexislefebvre** [comment]
Here is a new release: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/4.3.0

**Pull request merged**
