### PR TITLE
Disable autoexit #348

### PR DESCRIPTION
**Pull request by barthuttinga**

### CODE REVIEW

**Comment by lsmith77** [comment]
thank you for the PR. can you briefly state what the benefit is of this change. also please rebase on master.

**Comment by barthuttinga** [comment]
As stated in ticket #348 running `bin/console paratest:run -e test` on the command line results in creating the database schema, but then it exits. So it doesn't continue to load fixtures and run tests.

This seemed to be caused by the default behaviour of `Symfony\Component\Console\Application` which is to exit after running. I guess the default exit-behaviour of `Symfony\Component\Console\Application` has changed over time, but I haven't checked that.

I will rebase and update the PR.

**Comment by alexislefebvre** [comment]
@barthuttinga We have updated the test matrix and fixed bugs with versions so you can rebase your PR and tests should work again.

**Comment by barthuttinga** [comment]
@alexislefebvre I rebased on master, but still failing tests (no data fixtures found). No time now to have a look at right not, but willing to do so some other time.

**Comment by alexislefebvre** [comment]
@barthuttinga It looks like something failed during the rebase since there is more than one commit in this PR. This PR comes from the master branch of your fork, so it's a little bit more difficult to manage than a dedicated branch.

Maybe you should sync the master branch of your fork with the master of this repo, then create a branch and open a new PR that will replace this one.

**Comment by barthuttinga** [comment]
@alexislefebvre Sorry for messing up... I reset my master branch to the upstream branch

**Comment by alexislefebvre** [comment]
@barthuttinga I don't understand why the paratest test is failing now, maybe the rebase I performed didn't work as expected. :disappointed_relieved:

**Comment by lsmith77** [comment]
I suspect the change does have a negative effect on paratest

**Comment by barthuttinga** [comment]
Looks like the test is broken. Since the paratest command exits after building the schema, it never tried to load the fixtures. With autoexit set to false and the (missing) data fixtures copied form Tests/App/DataFixtures and adjusting the number of expected tests/assertions it works for me.

One more thing, Paratest doesn't seem to work with PHPUnit 6.x, since it depends on the class PHPUnit_Runner_Version (and not the namespaced PHPUnit\Runner\Version). So I removed "^6.1" for "phpunit/phpunit" from composer.json (although this should probably be fixed in brianium/paratest rather than in this bundle).

**Comment by barthuttinga** [comment]
Although I had it working locally, Travis doen't agree... To be continued.

**Comment by lsmith77** [comment]
```
One more thing, Paratest doesn't seem to work with PHPUnit 6.x, since it depends on the class PHPUnit_Runner_Version (and not the namespaced PHPUnit\Runner\Version). So I removed "^6.1" for "phpunit/phpunit" from composer.json (although this should probably be fixed in brianium/paratest rather than in this bundle).
```

Did you report this issue?
That being said the project seems to be in a somewhat unclear state https://github.com/brianium/paratest/pull/290#issuecomment-353450290

**Comment by alexislefebvre** [comment]
@barthuttinga do you still need this? Can we close this somewhat old issue?

**Comment by barthuttinga** [comment]
@alexislefebvre No, not relevant to me anymore. You can close it. Thanks

**Pull request closed without merging**
