### PR TITLE
2.x: Add tests with fixtures loading in setUp

### PR DESCRIPTION
**Pull request by alexislefebvre**

### CODE REVIEW

**Comment by alexislefebvre** [comment]
See #470

**Comment by alexislefebvre** [comment]
With database cache, users loaded from backup have ids from 3 to 12 instead of 1 to 10, this breaks tests.

**Comment by alexislefebvre** [comment]
I had to reset `AUTO_INCREMENT` so that the database cache load data with the same ids than before, but I'm not sure if this change is a good idea…

**Comment by dbu** [comment]
i guess the tests relying on a specific autoincrement are a bit of a dangerous idea. but looking at the [documentation](https://oracle-base.com/articles/mysql/mysql-how-truncate-table-affects-auto-increment), truncate did reset the autoincrement, so i think its good to reset it.

**Pull request merged**
