### PR TITLE
Webtestcase: Extract some fixtures methods

### PR DESCRIPTION
**Pull request by alexislefebvre**
to the new FixturesLoader class

### CODE REVIEW

**Comment by alexislefebvre** [comment]
It would be better to move all the code related to fixtures in a new class  but it's impossible because it would break the callbacks calls. So this is a compromise.

**Comment by lsmith77** [comment]
any specific reason why you made the implementation using static methods? limits the ability to extend if needed.

**Comment by alexislefebvre** [comment]
No I had no reason to declare the methods as static. But since it calls functions directly like `FixturesLoader::locateResources(…);`, can `FixturesLoader` be extended?

**Comment by lsmith77** [comment]
well if you add a factory method to the base class or make it an optional parameter then yes ..

**Comment by alexislefebvre** [comment]
I remember now why I declared static methods: it was easier to use them since it doesn't require to instantiate an object before calling the methods from `FixturesLoader`.

> well if you add a factory method to the base class or make it an optional parameter then yes ..

I think that I understand your idea now.

Would adding a method like `protected function getFixturesLoader() {}` in `WebTestCase` that

1. return an instance of `FixturesLoader` or instantiate an object then return it
2. can be overridden by any child class

is a good solution?

**Comment by lsmith77** [comment]
yeah .. I think so 

(sorry for the late reply)

**Comment by alexislefebvre** [comment]
This should be done with traits: https://github.com/liip/LiipFunctionalTestBundle/issues/332#issuecomment-329958638

**Pull request closed without merging**
