### PR TITLE
[2.x] Allow static assert calls

### PR DESCRIPTION
**Pull request by alexislefebvre**
Port of #445

### CODE REVIEW

**Comment by scaytrase** [comment]
@alexislefebvre Is failure related to the patch? Or it should be fixed somewhere else?

**Comment by alexislefebvre** [comment]
I haven't investigated on the failure yet.

**Comment by alexislefebvre** [comment]
It looks like the error is unrelated to this PR.

**Comment by alexislefebvre** [comment]
The error is `1) Liip\FunctionalTestBundle\Tests\Test\WebTestCaseConfigPhpcrTest::testLoadFixturesPhPCr
Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot dump definitions which have method calls.`.

It looks like the error comes from Symfony: https://github.com/symfony/symfony/issues/28296

**Pull request merged**
