### PR TITLE
Travis CI: Use Ubuntu Trusty

### PR DESCRIPTION
**Pull request by alexislefebvre**
See #326.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
There was a problem while creating the container:

> sudo service mysql start
> start: Job failed to start

**Comment by z38** [comment]
The failure might be related to travis-ci/travis-ci#7790 which mentions the same issues when switching to Trusty.

**Comment by alexislefebvre** [comment]
Thanks for the information @z38. We'll have to wait for the MySQL bug to be fixed before upgrading the Ubuntu version onTravis CI.

**Comment by alexislefebvre** [comment]
Thanks for the information @z38. We'll have to wait for the MySQL bug to be fixed before upgrading the Ubuntu version on Travis CI.

**Comment by z38** [comment]
According to the reports in travis-ci/travis-ci#8137, the bug seems to be fixed. So in theory, the version upgrade should work now.

**Comment by alexislefebvre** [comment]
Thanks for the updates @z38! I'm merging since it works now.

**Pull request merged**
