### PR TITLE
using assertValidationErrors() requires Symfony 2.5+

### PR DESCRIPTION
**Pull request by lsmith77**
related to https://github.com/liip/LiipFunctionalTestBundle/issues/177

### CODE REVIEW

**Comment by lsmith77** [comment]
@jmclean can you have a look at this?

**Comment by jmclean** [comment]
Looks good to me. Needs another note in the readme that assertStatusCode also requires version 2.5 (in addition to assertValidationErrors). Then the `symfony/validator` constraint can be removed from composer.json and it's good to go!

**Comment by alexislefebvre** [comment]
I think `if (interface_exists('Symfony\Component\Validator\Validator\ValidatorInterface')) {` is used to test that Symfony 2.5+ is used. But this interface exists with the last version of Symfony 2.3 and I have an error when I launch tests, it seems that `$loader->load('validator.xml');` is called with Symfony 2.3 too. The error in the following test seems to be caused by this code: https://travis-ci.org/alexislefebvre/LiipFunctionalTestBundle/jobs/97578616

**Comment by jmclean** [comment]
I'm pretty sure that error is coming from the constraint on symfony/validator in this bundle's composer.json. It's resulted in you getting version 2.6 of the validator but version 2.3 of the symfony core. @lsmith77 the symfony/validator line can just be removed from composer.json now. It's indirectly required by symfony/framework-bundle and the version isn't a strict requirement any more.

**Pull request merged**
