### PR TITLE
add append feature for sqlite on load fixtures method

### PR DESCRIPTION
**Pull request by almacbe**
I realize that I forget to add the append feature to SQLite. I've added it to this PR.

### CODE REVIEW

**Comment by almacbe** [comment]
And... how could I test this feature? I am not sure how to create a test in an environment with SQLite config.

**Comment by alexislefebvre** [comment]
Default configuration of tests uses SQLite:

https://github.com/liip/LiipFunctionalTestBundle/blob/ba8e654c798619aea58de1d3b912bcb718135340/tests/App/config.yml#L35

There is also some tests with MySQL, they are marked with `@group mysql` and they are ignored by default:

https://github.com/liip/LiipFunctionalTestBundle/blob/3bca1f2349c694f16670d6de63020c28c55df9fa/tests/Test/WebTestCaseConfigMysqlTest.php#L61

But Travis CI launch them:

https://github.com/liip/LiipFunctionalTestBundle/blob/48ec7c61ebcaf04955926a985b67d0389137a0ae/.travis.yml#L46

So as long as a test use the append feature, it will be tested with SQLite.

**Comment by almacbe** [comment]
I have added the test.

**Comment by almacbe** [comment]
Do you have some update about this PR?

**Comment by alexislefebvre** [comment]
Thanks!

**Pull request merged**
