### PR TITLE
Fix new static method getContainer in KernelTestCase collision

### PR DESCRIPTION
**Pull request by k20human**
Proposition to fix issue #583

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Awesome, thanks!

Our test suite is outdated. In the file `.github/workflows/tests.yml`, please replace `5.1` with `^5.3`.

**Comment by k20human** [comment]
Thanks @alexislefebvre it's done ;)

**Comment by alexislefebvre** [comment]
Thanks! You'll find it in the last release: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/4.4.0

**Comment by k20human** [comment]
Awesome, thanks, it will help us a lot :)

**Pull request merged**
