### PR TITLE
Use PSR 4 directory structure

### PR DESCRIPTION
**Pull request by alexislefebvre**
Use commit from #359

Replaces #324

### CODE REVIEW

**Comment by alexislefebvre** [comment]
@Jean85 @lsmith77 Can you please give your advice about this PR?

I thought that it was better to perform changes on master instead of 2.0 as long as it was possible. And do only BC changes on the 2.0 branch.

**Comment by lsmith77** [comment]
see my response in the other PR, imho its not worth it to try and get those changes into master where we have to ensure 100% BC.

**Comment by alexislefebvre** [comment]
Thanks for your answer, I think that there is no risk of BC break since I only moved some files. The namespace is the same as before.

**Comment by alexislefebvre** [comment]
Well, you're right. We don't need this on master.

**Pull request closed without merging**
