### PR TITLE
Updated validator's URL added in #211: http://validator.nu/ now uses HTTPS

### PR DESCRIPTION
**Pull request by alexislefebvre**
Added test of code snippet
Revert some unnecessary changes from #211 and cc2c9efc64d09cace82e701deb44bb071ab6b6b6

### CODE REVIEW

**Comment by alexislefebvre** [comment]
In #211, I changed some code because http://validator.nu/ returned a 301 status code, this was unnecessary.

**Comment by lsmith77** [comment]
thx again @alexislefebvre .. I think by now you have shown your commitment and knowledge .. do you want to get push access to this repo?

**Comment by alexislefebvre** [comment]
@lsmith77 thanks for the offer! For the moment, I don't have any problem with using Pull Requests, it avoids push errors, automates tests and it's easier for you to review. And I think I have already done much of the changes I wanted. So we can continue to work through Pull Requests and see in the future if push access may ease development. Thanks.

**Comment by lsmith77** [comment]
alright!

**Comment by alexislefebvre** [comment]
@lsmith77 Finally, I would be pleased to have push access to this repo. I could use it for changes related only to tests (e.g my pending PR) which won't break anything and use PR for changes related to the behaviour of the Bundle. Thanks.

**Comment by lsmith77** [comment]
done

**Comment by alexislefebvre** [comment]
Thanks a lot! :)

**Pull request merged**
