### PR TITLE
Append fixtures

### PR DESCRIPTION
**Pull request by pstephenson02**
While I don't necessarily want to add more to this loadFixtures method, this functionality is important to the test suite I work on. I can add documentation pending any changes/updates during review.

### CODE REVIEW

**Comment by lsmith77** [comment]
can you have a look if that method could be refactored a bit? .. maybe just splitting it up into multiple private methods

**Comment by pstephenson02** [comment]
Sure. I'm pretty busy until this weekend but I'll do what I can. I noticed this lingering issue: https://github.com/liip/LiipFunctionalTestBundle/issues/6 which is a lot more work but probably worth revisiting

**Comment by lsmith77** [comment]
also needs a rebase

**Comment by lsmith77** [comment]
ping :-/

**Comment by almacbe** [comment]
Hi, I think this is a really good feature @pstephenson02 . Actually I need it now. If no one have time I can try to finish it.

@lsmith77 the idea is rebase this PR and what else? because it will be a BC, maybe we could create another function that add the new append parameter and we could use the same code and I could try to refactor a bit more and I could try don't repeat the code. What do you think?

**Comment by lsmith77** [comment]
@almacbe well we are preparing a 2.x release so BC breaking features should go into that branch. I don't know exactly how far along that branch is, but I think it should be in a workable state and likely released soon.

/cc @alexislefebvre

**Comment by Jean85** [comment]
Mind that the 2.x branch uses (indirectly) `nelmio/alice` v3.

**Comment by almacbe** [comment]
@Jean85 I am not sure why you warn me about that. Are there something that I have to take care?

**Comment by Jean85** [comment]
They changed a lot of stuff (internally) between those two major version, see https://github.com/nelmio/alice/blob/master/UPGRADE.md

**Comment by alexislefebvre** [comment]
The 2.x is the branch of the future major release, an alpha version was published today, breaking changes must go on this branch. See #381 for further information.

**Comment by pstephenson02** [comment]
Hey everyone, I'm sorry I never had a chance to actually finish this work. Unfortunately I'm no longer in a position to do so. I'm closing this PR so someone else can implement this feature if it's still a priority.

**Pull request closed without merging**
