### PR TITLE
Fixes #257: Check all the dependencies when checking database cache

### LINKED ISSUE #257: Database doesn't reload if a dependent fixture changes
My database didn't update when I changed the contents of a dependent fixture:

Test case:
```php
$this->loadFixtures([AFixture::class]);
```
AFixture:
```php
class AFixture implements DependentFixtureInterface {
// ...
    public function getDependencies()
    {
        return [DependencyFixture::class];
    }
}
```
config_test.yml
```yml
liip_functional_test:
    cache_sqlite_db: true
```
If you now alter the `DependencyFixture` class, the database is not updated when the test case is executed. (using Symfony 3 + latest version of the bundle).

### PR DESCRIPTION
**Pull request by alexislefebvre**
Fixes #257

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Can someone please review this PR? I hope that it won't break anything.

ping @cmfcmf

Thanks.

**Comment by alexislefebvre** [comment]
This replaces #259.

**Comment by cmfcmf** [comment]
This looks good. I'll test this myself this evening.

**Comment by alexislefebvre** [comment]
With this change, it will call [`getFixtureLoader(…)`](https://github.com/liip/LiipFunctionalTestBundle/blob/master/Test/WebTestCase.php#L623-L641), that will then call [`Doctrine\Common\DataFixtures#addFixture(…)`](https://github.com/doctrine/data-fixtures/blob/81cd269006b37452389801e05974ba05bcd7005b/lib/Doctrine/Common/DataFixtures/Loader.php#L118-L143). This last function will fetch all the dependencies, recursively. This should work!

**Comment by alexislefebvre** [comment]
TODO: In the test, check that the backup is not refreshed if the fixture is not updated.

**Comment by alexislefebvre** [comment]
@cmfcmf please let me know when you will have tested the change.

**Comment by cmfcmf** [comment]
Confirmed working :+1: Thank you!

**Pull request merged**
