### PR TITLE
Symfony 5 support

### PR DESCRIPTION
**Pull request by gregurco**
Hello,

here are changes to support Symfony 5.

Resolves: #554
Closes: #555

### CODE REVIEW

**Comment by alexislefebvre** [comment]
That looks great!

**Comment by gregurco** [comment]
Hello @alexislefebvre 
Today I plan to test these changes with project migrating from SF4 to SF5. I will write the result after the test.

**Comment by gregurco** [comment]
@alexislefebvre could you help me with next error?

```
There was 1 failure:

1) Liip\Acme\Tests\Command\ParatestCommandTest::testParatest
Failed asserting that 'Error : Install paratest first\n' contains "Running phpunit in 3 processes with vendor/bin/phpunit".

/home/travis/build/liip/LiipFunctionalTestBundle/tests/Command/ParatestCommandTest.php:50
```

I see that paratest is not installed in dev. How tests worked before? Should it be installed or somehow mocked in tests?

**Comment by alexislefebvre** [comment]
I was stuck too with paratest in #555

I haven't checked yet how much effort are required to support paratest and Symfony 5 in the same time.

Feel free to remove the paratest test in this PR, so we can merge it and then publish a new unstable release. We'll evaluate the case of paratest later.

**Comment by gregurco** [comment]
@alexislefebvre good idea! Done! I also will check how to fix integration with paratest.

**Comment by alexislefebvre** [comment]
Thanks for the great work!

Here is an alpha release with these changes: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/3.4.0-alpha1

**Pull request merged**
