### PR TITLE
Replace Client by KernelBrowser for Symfony 4.3 compatibility.

### PR DESCRIPTION
**Pull request by gnutix**
See #509

### CODE REVIEW

**Comment by alexislefebvre** [comment]
You can add Symfony 4.3 in the matrix of `.travis.yml`.

In the issue you wrote:

> TypeError: Return value of Liip\FunctionalTestBundle\Test\WebTestCase::makeClient()
must be an instance of Symfony\Bundle\FrameworkBundle\Client, instance of
Symfony\Bundle\FrameworkBundle\KernelBrowser returned

I don't understand why we must return `KernelBrowser` when the error stats that it must be an instance of `Client`. :thinking:

**Comment by gnutix** [comment]
> I don't understand why with this PR we return KernelBrowser when the error states that it must be an instance of Client.

The error is that LiipFunctionalTestBundle's WebTestCase defines a strict return type of the "Client" class, but Symfony 3.4 replaced it by "KernelBrowser" (which is basically empty and simply extends the Client). So PHP doesn't like that Symfony's code return an instance of "KernelBrowser" and LiipFunctionalTestBundle's WebTestCase try to return a "Client".

**Comment by gnutix** [comment]
@alexislefebvre Any idea how I can set the `"minimum-stability": "beta"` only for one test matrix? There's no composer flag for that AFAIK.

**Comment by alexislefebvre** [comment]
You can require `^4.3@alpha`, it should work: https://semver.mwl.be/#?package=symfony%2Fsymfony&version=%5E4.3&minimum-stability=alpha

**Comment by gnutix** [comment]
The tests are passing with Symfony 4.3.0-BETA1 (and failing everywhere else). Anything else I should do?

**Comment by alexislefebvre** [comment]
Thanks for the PR.

We should try to use a compatibility layer instead of having a version of the bundle that require Symfony 4.3.

See my comments here: https://github.com/liip/LiipFunctionalTestBundle/issues/509#issuecomment-494739539

**Comment by gnutix** [comment]
Replaced by https://github.com/liip/LiipFunctionalTestBundle/pull/512

**Pull request closed without merging**
