### PR TITLE
[WIP] Refactoring work with db

### PR DESCRIPTION
**Pull request by alekseytupichenkov**
- [ ] Refactor code
- [ ] Write tests
- [ ] Rewrite mysql/mongodb backup and restore without using console command
- [ ] Mark old method as deprecated
- [ ] Write usage and examples in Readme
- [ ] Command to clear backup cache

### CODE REVIEW

**Comment by alexislefebvre** [comment]
@alekseytupichenkov It looks like there are a lot of changes, would it break how fixtures are loaded?

**Comment by alekseytupichenkov** [comment]
@alexislefebvre nope, I'll add fallback methods for it

**Comment by alexislefebvre** [comment]
I changed some things in #476, you'll have to rebase your PR, sorry.

**Comment by alexislefebvre** [comment]
I'm closing this since fixtures loading has been moved to https://github.com/liip/LiipTestFixturesBundle

**Pull request closed without merging**
