### PR TITLE
Fix sensio insights violations

### PR DESCRIPTION
**Pull request by Aerendir**

### CODE REVIEW

**Comment by alexislefebvre** [comment]
I'm sorry to bother you, but you can [squash the changes](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) in order to keep only one commit per Pull Request. This will update this PR automatically and remove the previous commits.

**Comment by Aerendir** [comment]
I did my best...

**Comment by alexislefebvre** [comment]
:+1: 

The squash worked, there is only two commits now. :)

**Comment by Aerendir** [comment]
Now I cannot try again, but wait, and I'll do better... I think I've understood how to do...

**Comment by alexislefebvre** [comment]
The last time I squashed commits, I used `git rebase -i HEAD~2` several times in order to rewrite the history, I found it easier that merging more than 2 commits.

Now I use `git commit --amend --date=$(date -R)` in order to update the last commit, `--amend` tells git to edit the last commit and `--date=$(date -R)` to update the date of the commit.

**Comment by Aerendir** [comment]
Done! Only the command `--date=$(date -R)` seems not working... For now!

**Comment by alexislefebvre** [comment]
You can try this if you want to update the date of the commit: `git commit --amend --date=now`

**Comment by Aerendir** [comment]
@alexislefebvre , ok, thanks! :)

**Pull request merged**
