### PR TITLE
Add DisableCacheDb annotation

### PR DESCRIPTION
**Pull request by magnetik**
It's #480 !

I did a little cleanup of some `@IgnoreAnnotation` missing.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
LGTM, thanks!

**Comment by alexislefebvre** [comment]
Could you please add `@DisableCacheDb()` in https://github.com/liip/LiipFunctionalTestBundle/blob/2.x/CHANGELOG.md ?

I'm wondering now, should it be called `@DisableDbCache()` or a move verbose name `@DisableDatabaseCache()`?

**Comment by magnetik** [comment]
I did `DisableCacheDb` to mirror the config that is called `cache_db`. I was not so pleased about the name but `@DisableDatabaseCache` looks much better

**Comment by magnetik** [comment]
I've renamed the annotation

**Comment by alexislefebvre** [comment]
Great, thanks for the PR and the changes!

**Comment by magnetik** [comment]
Not so much hype about this change, but can this be shipped in an new alpha to see if it can get more traction?

**Comment by alexislefebvre** [comment]
Thanks for the reminder, the PR is merged and a new version has been published: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/2.0.0-alpha14

**Pull request merged**
