### PR TITLE
Fix `getVerbosityLevel()` exception.

### PR DESCRIPTION
**Pull request by Aerendir**

### CODE REVIEW

**Comment by Aerendir** [comment]
@alexislefebvre This should fix the error you reported about two days ago... Can you check please?

**Comment by alexislefebvre** [comment]
There is a misunderstanding.

In my comment I was pointing the fact that the `throw new \OutOfBoundsException(` block seems to be unreachable.

If in the `Tests/Command/CommandTest.php` file I change `$this->setVerbosityLevel('debug');` to `$this->setVerbosityLevel('foo');`, I have a PHP error:

1) Liip\FunctionalTestBundle\Tests\Command\CommandTest::testRunCommandVerbosityDebug
constant(): Couldn't find constant \Symfony\Component\Console\Output\StreamOutput::VERBOSITY_FOO

> .../LiipFunctionalTestBundle/Test/WebTestCase.php:170
> .../LiipFunctionalTestBundle/Test/WebTestCase.php:136
> .../LiipFunctionalTestBundle/Tests/Command/CommandTest.php:179
> .../vendor/phpunit/phpunit/src/TextUI/Command.php:155
> .../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:106

Shouldn't it throw an `OutOfBoundsException` exception with the help message you mentioned?

**Comment by alexislefebvre** [comment]
Please see this test I added: https://github.com/alexislefebvre/LiipFunctionalTestBundle/commit/f4cc1d3eef9c7001f97b5759a6d6247b20a1c3c6

And how the test fail: https://travis-ci.org/alexislefebvre/LiipFunctionalTestBundle/builds/105887198

I tried to change `(null === constant($verbosity))` to `(! defined($verbosity))` and it worked, PHP didn't reported any error.

**Comment by Aerendir** [comment]
Aaaaa, ok, now I'm understanding!

Ok, I'll change again the code... I'm now understand what you are saying. At the time I didn't noticed the difference...

**Comment by alexislefebvre** [comment]
Can you please copy and paste the test from https://github.com/alexislefebvre/LiipFunctionalTestBundle/commit/f4cc1d3eef9c7001f97b5759a6d6247b20a1c3c6 in your PR? It will check that the Exception will be thrown. Thanks.

**Comment by lsmith77** [comment]
ping

**Comment by alexislefebvre** [comment]
@lsmith77 you can merge it, I'll add the corresponding test later.

**Comment by Aerendir** [comment]
Done! Excuse me for the late response!
@lsmith77 thank you for the [mention](https://github.com/liip/LiipFunctionalTestBundle/releases/tag/1.4.0). It make me very happy! Honoured to contribute :)

**Comment by alexislefebvre** [comment]
@Aerendir No problem. :-)

**Pull request merged**
