### PR TITLE
FlintCI integration

### PR DESCRIPTION
**Pull request by Soullivaneuh**
As proposed on https://github.com/liip/LiipFunctionalTestBundle/issues/338#issuecomment-356663407, here is a FlintCI configuration: 

I also took permissions to add some extra CS rules on .php_cs. Tell me if you want to change some!

To enable FlintCI, just connect here: https://flintci.io and enable your repository. You may want to change some settings. After done, the first analysis will be done on next push. Closing and re-opening this PR may do the thing too.

As you can see, this way permit to access the full configuration of php-cs-fixer v2 and both cli and diff view. Plus, other services are available like yamllint.

The interface is still quite primitive, I'm on heavy development of the app. Don't hesitate to give some feedbacks! :+1: https://gitlab.com/flintci/flintci

Note: I let the StyleCI configuration for now. I let you decide to keep both or completely migrate to FlintCI.

Regards.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
@lsmith77 I think that we should merge this on the 2.x branch instead of master, what do you think?

(I'm sorry if that will require more work from you @Soullivaneuh)

**Comment by Soullivaneuh** [comment]
@alexislefebvre no problem. :+1: 

But I think it should be merge on both (maybe by fallback merge) if you don't want FlintCI yelling in each push on `master`.

**Comment by alexislefebvre** [comment]
Right, I'll explain why I thought about the 2.x branch: @lsmith77 suggested to keep `master` as a sort of LTS release where we will fix bugs and use the 2.x branch for new features: https://github.com/liip/LiipFunctionalTestBundle/pull/359#issuecomment-354276234

While the changes is this PR are only related to style and looks like, I think that there is a risk of BC break. So I suggest to keep the code in master as is and only use this new CI on the 2.x branch.

**Comment by lsmith77** [comment]
I don’t have a strong opinion on this either way.

**Comment by Soullivaneuh** [comment]
@alexislefebvre As you said, it's just coding style enforcement and the tests still pass.

I did a cherry-pick of this PR on 2.x, only those file was conflicted:

```
Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   src/Test/WebTestCase.php
	both modified:   tests/App/AppKernel.php
	both modified:   tests/Test/WebTestCaseConfigMysqlTest.php
	both modified:   tests/Test/WebTestCaseConfigTest.php
	both modified:   tests/Test/WebTestCaseTest.php
```

So I'll reset them and run php-cs-fixer again. PR is coming.

I let you the choice to merge both PR or only one of them.

Note: I opened an issue about branches exclusion: https://gitlab.com/flintci/flintci/issues/103
Don't hesitate to give any input on it! :+1:

**Comment by alexislefebvre** [comment]
@lsmith77 

> I don’t have a strong opinion on this either way.

Me neither. I let you merge this PR if it's OK for you.

**Comment by lsmith77** [comment]
if course this then needs to be merged into 2.x as well ..

**Comment by alexislefebvre** [comment]
@lsmith77 I'm not admin on this repo, can you please enable the CI from @Soullivaneuh?

> To enable FlintCI, just connect here: https://flintci.io and enable your repository. You may want to change some settings. After done, the first analysis will be done on next push. Closing and re-opening this PR may do the thing too.

**Comment by lsmith77** [comment]
done .. hopefully :)

**Comment by Soullivaneuh** [comment]
@lsmith77 did you activate FlintCI **after** merging the PRs? I can't see any analysis right now.

**Comment by lsmith77** [comment]
yes .. it was after merging.

**Comment by Soullivaneuh** [comment]
@lsmith77 Right, it should be ok for later. :wink:

**Pull request merged**
