### PR TITLE
[2.x] Remove hard dependency on doctrine/common

### PR DESCRIPTION
**Pull request by alexislefebvre**
Related to #434, I think that we don't need this hard dependency.

### CODE REVIEW

**Comment by Jean85** [comment]
Isn't it used anywhere in the code?

**Comment by alexislefebvre** [comment]
I remember it only now, I think that it's used to read annotations in https://github.com/liip/LiipFunctionalTestBundle/blob/294f8127df03923a16354e6f1062f5172be06994/src/Annotations/QueryCount.php#L17-L18

So removing `doctrine/common` seems wrong…

**Comment by Jean85** [comment]
Well, that highlights that we do not have a test in place, probably...

**Comment by alexislefebvre** [comment]
`doctrine/common` was installed on Travis CI after I removed it: https://travis-ci.org/liip/LiipFunctionalTestBundle/jobs/405112576

So it must be a dependency of one of these dependencies: https://github.com/alexislefebvre/LiipFunctionalTestBundle/blob/d1335ad3a37c970a152b533e78ba091fa6370c81/composer.json#L18-L33

`"doctrine/orm": "^2.6",` requires `doctrine/common` so it will always be installed with current versions of Doctrine ORM.

If we don't install `doctrine/orm`, on the CI, we won't be able to count number of queries, I don't know how we can test the state where `doctrine/common` is not installed but we can still run internal tests.

**Comment by Jean85** [comment]
Common is a dependency of Doctrine 2.6, but I think it will be dropped in 2.7, so we cannot rely on that...

**Comment by alexislefebvre** [comment]
We may rely on https://github.com/doctrine/annotations if we only used `doctrine/common` to read annotations.

**Comment by alexislefebvre** [comment]
See https://github.com/liip/LiipFunctionalTestBundle/issues/434#issuecomment-406899337: we have to require the new doctrine packages that provide features from `doctrine/common` that this bundle uses.

**Comment by Majkl578** [comment]
> Common is a dependency of Doctrine 2.6, but I think it will be dropped in 2.7, so we cannot rely on that...

It won't, only in ORM 3.0 (due to dependency on doctrine/common's proxy generator). But it'd be a good move to depend on specific doctrine/* packages (doctrine/annotations in your case) instead of doctrine/common.

General rule of thumb: never rely on indirect dependencies - they may be dropped or bumped to a new major version without you noticing (since you have no constraint against the indirect dependency). 👍 

Also I recommend https://github.com/maglnet/ComposerRequireChecker, it'll spot dependencies that are not directly depended upon.

**Pull request merged**
