### PR TITLE
Fixed auth array_merge params

### PR DESCRIPTION
**Pull request by Arthurhall**
Parameter passed to "makeClient()" should override the default one in config_test.yml.

### CODE REVIEW

**Comment by Arthurhall** [comment]
I just understand, for overriding i need to do : 

$client = static::makeClient(false, array(
    'PHP_AUTH_USER' => 'alice',
    'PHP_AUTH_PW' => 'testtttt',
));

But I think it is confusing ...

**Comment by lsmith77** [comment]
I think what could make sense is the following:

```
$client = static::makeClient(array(
    'username' => 'alice',
    'password' => 'testtttt',
));
```

**Comment by Arthurhall** [comment]
Why not, the first parameter would be a boolean or an array ...

**Comment by lsmith77** [comment]
yup .. can you update your PR accordingly?

**Comment by Arthurhall** [comment]
ok i will

**Comment by lsmith77** [comment]
needs a rebase

**Comment by lsmith77** [comment]
BTW .. I would recommend to create a new PR starting from master and cherry picking your change .. all the style fixes were already done there.

**Comment by Arthurhall** [comment]
ok, rebase done

**Comment by lsmith77** [comment]
there is still a small style issue to fix

**Comment by lsmith77** [comment]
btw these are issues introduced by your changes this time ..

**Comment by Arthurhall** [comment]
Yep sorry, fixed.

**Comment by lsmith77** [comment]
looks like this caused a regression https://github.com/liip/LiipFunctionalTestBundle/issues/192

**Pull request merged**
