### PR TITLE
[WIP] Sf 6 compatibility

### PR DESCRIPTION
**Pull request by magnetik**
Trying to make this bundle compatible with Symfony 6

ref #597

### CODE REVIEW

**Comment by xvilo** [comment]
Hi @magnetik, what is the status of this PR? Is it already finished, or do you need help>

**Comment by kl3sk** [comment]
Hi @magnetik, does @alexislefebvre solution solved your problems ?
Have this package available for SF6 will be great.

**Comment by gjuric** [comment]
Can somebody with permissions rerun the tests so we can see what is failing? The current logs are not being shown since a lot of time has passed since the actions were run.

**Comment by alexislefebvre** [comment]
I can't rerun these jobs.

**Comment by alexislefebvre** [comment]
In order to have the errors, I opened another PR from this one: #603

The current issue is that `framework.session.storage_factory_id` replaces `framework.session.storage_id` since Symfony 6.0, we have to write 2 different config files.

---

One test of `AllowedQueriesExceededException` and some other things were broken on the main branch, I fixed these issues in another PR: #604 I'm not happy with the change of `max_query_count` from `1` to `0` in the internal tests but if it allow to have a version compatible with Symfony 6, it will be worth it.

**Comment by alexislefebvre** [comment]
If you're interested in Symfony6, please review #603

**Comment by alexislefebvre** [comment]
Dear users, what methods from this bundle do you use? Which ones would you like to still use with Symfony 6?

**Pull request closed without merging**
