### PR TITLE
Make services public explicitly

### LINKED ISSUE #368: Services should be public for Symfony 4
To avoid this kind of error:

```
1) App\Tests\Controller\HookControllerTest::testNoAdminAccessWithRepositoryToken
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "liip_functional_test.exception_listener" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

/code/vendor/symfony/dependency-injection/Container.php:252
/code/vendor/liip/functional-test-bundle/Utils/HttpAssertions.php:65
/code/vendor/liip/functional-test-bundle/Test/WebTestCase.php:915
/code/tests/Controller/HookControllerTest.php:198
```

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #368

### CODE REVIEW

**Comment by alexislefebvre** [comment]
It looks like it covers more services than #367.

**Comment by Soullivaneuh** [comment]
@Jean85 Well, I don't know. At least the two of #367 are called by the container, so yes for them.

Maybe merge #367 first and see if we need more?

**Comment by alexislefebvre** [comment]
@Soullivaneuh I merged #367, I'll publish the 1.9.1 release soon.

**Comment by alexislefebvre** [comment]
@Soullivaneuh do you still have deprecations with the 1.9.1 version of this package? Can we close this PR and #368? Thanks.

**Comment by Soullivaneuh** [comment]
@alexislefebvre I didn't test yet, but the two services I need to be public are now public thanks to #367.

So I think we may close this one for now.

**Pull request closed without merging**
