### PR TITLE
Test HautelookAliceBundle with Faker Provider

### PR DESCRIPTION
**Pull request by alexislefebvre**
Thanks to @estahn.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
@estahn Can you please review this PR? Thanks.

**Comment by lsmith77** [comment]
FYI I bumped the composer.json branch alias https://github.com/liip/LiipFunctionalTestBundle/commit/8c4cd9f8bc646032f31f44e0c4c88476a8f5b1d9

**Comment by estahn** [comment]
@alexislefebvre You included you configuration in `AppKernel`, so wouldn't that change the conditions for all tests? Basically everything goes through Hautelook?

**Comment by alexislefebvre** [comment]
@estahn If your question is about all the tests when using this Bundle in a project, this won't change anything since this `AppKernel` is only loaded when testing this Bundle. In the context of this Bundle, only the test I added load the configuration (not yours as you explained [here](https://github.com/alexislefebvre/LiipFunctionalTestBundle/pull/23#issuecomment-186955084)). The other tests don't use Hautelook's Bundle. Does it answer your question?

**Comment by estahn** [comment]
@alexislefebvre Ah, yes. Great, good to go then.

**Pull request merged**
