### PR TITLE
#220. Type hint `$response` in `WebTestCase::isSuccessul()`.

### PR DESCRIPTION
**Pull request by Aerendir**

### CODE REVIEW

**Comment by lsmith77** [comment]
on my ipad atm and going by memory .. do we really have an HTTPFoundation Response here or is it not a debug client response?

**Comment by alexislefebvre** [comment]
I added a test for this function: https://github.com/liip/LiipFunctionalTestBundle/blob/8a337da9fd552709709d99985c14c814e29dd6c9/Tests/Test/WebTestCaseTest.php#L80

It looks consistent with the method: https://github.com/liip/LiipFunctionalTestBundle/blob/8a337da9fd552709709d99985c14c814e29dd6c9/Test/WebTestCase.php#L664

**Comment by Aerendir** [comment]
@alexislefebvre Very good! :+1:  :)

**Comment by alexislefebvre** [comment]
I just discovered it was discussed before in #147.

**Pull request merged**
