### PR TITLE
#224. Add `tearDown()` method to `WebTestCaseTest`.

### PR DESCRIPTION
**Pull request by Aerendir**

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Is it related to #218?

**Comment by Aerendir** [comment]
@tackerm , read this about the difference between the two: http://stackoverflow.com/questions/584960/whats-better-at-freeing-memory-with-php-unset-or-var-null

It seems that set the variable to `null` is a it faster than `unset` it.

**Comment by tackerm** [comment]
This may now be an academic excursion, but:

Setting a variable to `null` is 
* "faster" in terms of freeing up *some* memory *immediately*
* "slower" in terms of overall code execution (because of the additional cycles)

`unset`ing a variable is
* "better" in terms of freeing up *all* memory *eventually* (at the next gc cycle -> garbage collection must be enabled)
* "faster" in terms of overall code execution

In my own projects, memory consumption is **always** the limiting factor - I think the code execution time is neglectible (especially for tests), but the *some memory* vs. *all memory* issue can make quite a difference :wink: 

Anyways, any kind of cleanup is better than none, so :+1: :smile:

**Comment by Aerendir** [comment]
@tackerm , yes, maybe a simple academic excursion, but I'm interested in it as We should choose a way (and I have to choose one for my projects, too! :) ).

What do you prefer? Maybe we could use both of them?

**Comment by tackerm** [comment]
Well, this specific PR only affects the test which tests the bundle itself, so it doesn't really matter. But if you plan to add a `tearDown()` to `WebTestCase`, then I'd strongly recommend to use `unset()`.

**Comment by Aerendir** [comment]
:+1: Then I'll use `unset()`... I were on the same direction...

**Comment by lsmith77** [comment]
also the PR needs a rebase.

**Comment by Aerendir** [comment]
@lsmith77 , the PR is now ready!

**Comment by Aerendir** [comment]
It seems Scrutinizer failed in something... Is this a fault of mine? I think it isn't, but I may be wrong...

**Comment by lsmith77** [comment]
retriggered. lets see

**Pull request merged**
