### PR TITLE
#181 Add HautelookAliceBundle support forr custom provider / processor support

### PR DESCRIPTION
**Pull request by estahn**

### CODE REVIEW

**Comment by alexislefebvre** [comment]
You can add the Bundle in the `require-dev` part of `composer.json` in order to test it.

**Comment by alexislefebvre** [comment]
About the Travis CI failing test with `--prefer-lowest`, you can [skip the test](https://github.com/liip/LiipFunctionalTestBundle/blob/0b65790fc70095dacb9c54164996ea0559ef40a8/Tests/Test/WebTestCaseTest.php#L432-L434) if needed, because this option install old versions of bundles.

**Comment by estahn** [comment]
@alexislefebvre Thanks for the tip. I added the changes and squashed all commits.

@lsmith77 Good to go from my end.

**Comment by alexislefebvre** [comment]
@estahn If you want to test that the configuration is loaded, you can add the Alice configuration in [this config file](https://github.com/liip/LiipFunctionalTestBundle/blob/master/Tests/AppConfig/config.yml), and can move the new test to [`WebTestCaseConfigTest.php`](https://github.com/liip/LiipFunctionalTestBundle/blob/master/Tests/Test/WebTestCaseConfigTest.php) where the configuration file will be loaded. However it will require a bit more work because you'll have to implement a custom provider. Do as you please. :)

**Comment by lsmith77** [comment]
I guess that can be done in a follow up PR.

**Comment by estahn** [comment]
@lsmith77 Would you mind creating a release including this?

**Comment by alexislefebvre** [comment]
@estahn How can we document this new feature? Add a note about the declaration of a [HauteLook Alice service](https://github.com/liip/LiipFunctionalTestBundle/issues/181#issuecomment-184238934) in `README.md`?

**Comment by estahn** [comment]
@alexislefebvre Yes, we can add that to the README. I'd suggest to mention that the Hautelook Alice service will be used when defined and that custom processors/providers can be implemented through this.

**Comment by lsmith77** [comment]
can you send a PR then I will make a release. thx

**Comment by alexislefebvre** [comment]
@estahn I added some assertions using a faker provider but it doesn't work, can you please take a look? Thanks.

It's in https://github.com/alexislefebvre/LiipFunctionalTestBundle/pull/23

**Comment by alexislefebvre** [comment]
Here are the relevant PRs about test and documentation: https://github.com/liip/LiipFunctionalTestBundle/pull/246 and https://github.com/liip/LiipFunctionalTestBundle/pull/247

**Pull request merged**
