### PR TITLE
Separate db tool and db backup/restore services for version 1.9.3

### PR DESCRIPTION
**Pull request by alekseytupichenkov**
Provide services for backup/restore different database and refactoring code

### CODE REVIEW

**Comment by alexislefebvre** [comment]
As I [wrote it earlier](https://github.com/liip/LiipFunctionalTestBundle/pull/396#issuecomment-365266546), and even if it's an excellent work, we'll probably keep the 1.x branch as is, by fixing bugs but not adding features. Do you agree @lsmith77? Thanks.

**Comment by lsmith77** [comment]
yeah. lets keep 1.x around for a little bit. until November specifically: https://symfony.com/roadmap?version=2.8#checker

**Comment by lsmith77** [comment]
buts lets be conservative here with changes. ie. only bug fixes. no new features or refactorings.

**Comment by alexislefebvre** [comment]
Thanks @alekseytupichenkov but we decided to keep the 1.x branch as is, I'm closing this PR.

**Comment by powerpd** [comment]
@alexislefebvre 
I think you need to close https://github.com/liip/LiipFunctionalTestBundle/pull/403 also

**Pull request closed without merging**
