### PR TITLE
WebTestCase makeClient method update

### PR DESCRIPTION
**Pull request by DamienVauchel**
Hi,

I detected an useless if condition on authentication so I removed it.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Thanks, with this change we can't pass an array as the first parameter. That's why there are 2 conditions. It looks like it's a breaking change and it should break internal tests of the bundle.

**Comment by DamienVauchel** [comment]
My bad! I didn't check it.

Don't you think it is kinda dirty to accept that an array argument could be a boolean (or a boolean argument be an array)? 
(Not a mean/troll question, I don't know if my english is perfect^^", it is a real question)

**Comment by alexislefebvre** [comment]
I agree with you, the fact that the first parameter accept two different types is confusing.

We should refactor this for the 3.x release, see #496 

We may add a `makeAuthentifiedClient()` method in order to reduce the size and complexity of `makeClient()`.

**Comment by alexislefebvre** [comment]
See #506.

**Pull request closed without merging**
